---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vntopo-controller-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - vntopo.bupt.site
  resources:
  - vnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vntopo.bupt.site
  resources:
  - vnodes/finalizers
  verbs:
  - update
- apiGroups:
  - vntopo.bupt.site
  resources:
  - vnodes/status
  verbs:
  - get
  - patch
  - update
