---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vntopo-controller
  namespace: vntopo-system
  labels:
    app.kubernetes.io/name: vntopo-operator
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vntopo-agent
  namespace: vntopo-system
  labels:
    app.kubernetes.io/name: vntopo-operator
    app.kubernetes.io/component: agent
