apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - daemonset.yaml
images:
  - name: agent
    newName: docker.io/bupt-aiops/vntopo-agent
    newTag: dev
  - name: init
    newName: docker.io/bupt-aiops/vntopo-init
    newTag: dev
